### ISSUE TITLE
Several issues reported

### ISSUE THREAD

**Issue by mousesalt** [AxerBot/axer-bot#150]
- commands are still working even /cooldown used to channels.
- missing respond to `favorites` argument in /mapsetrank.
- `help` for slash arguments commands such reminder should be using slash instead prefix.
- link map in /recent doesn't valid.

**Comment by Sebola3461** [comment]
There's nothing wrong with cooldowns. Cooldowns doesn't works with slash commands, slash commands are configurable in your discord client. Check `Channel Settings > Permissions > Allow Application Comands`

**Comment by Sebola3461** [comment]
Fixed error with `/mapsetrank`

**Comment by Sebola3461** [comment]
Scores that aren't top plays are deleted after 24 by bancho.

**Comment by Sebola3461** [comment]
Help will be moved later

**Comment by mousesalt** [comment]
> There's nothing wrong with cooldowns. Cooldowns doesn't works with slash commands, slash commands are configurable in your discord client. Check `Channel Settings > Permissions > Allow Application Comands`

yes i did. however its still appears on cooldowned channels.

or something its excluded for admin only, so only admins can uses slash commands to cooldowned channels?

**Comment by Sebola3461** [comment]
Admins can use in all channels. Same for cooldown system.
